name: Sample Workflow
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Build Step 1'
        uses: ./.github/actions/mock
        with:
          MOCK_STEP_NAME: "Build Step 1"

      - name: 'Build Step 2'
        uses: ./.github/actions/mock
        with:
          MOCK_STEP_NAME: "Build Step 2"

      - name: 'Build Step 3'
        uses: ./.github/actions/mock
        with:
          MOCK_STEP_NAME: "Build Step 3"